

spring:

  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true

  #
#  jpa:
#    properties:
#      hibernate:
##        dialect: com.siukatech.poc.react.backend.module.core.dialect.data.MyPostgreSQLDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: none
#        show-sql: true
#        format-sql: true
#
#  datasource:
#    url: jdbc:postgresql://localhost:25432/toydb
#    username: toy_web
#    #password: ${POSTGRES_PASSWORD:mypass}
#    password: mypass
#    initialization-mode: always
#    initialize: true
#    bak-schema: classpath:/schema.sql
#    continue-on-error: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: ${oauth2-client-redirect-uri}

        provider:
          keycloak:
            authorization-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/auth
            token-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/token
            user-info-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/userinfo
            issuer-uri: ${oauth2-client-keycloak}/realms/${client-realm}
            jwk-set-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
#            user-info-authentication-method:

      resource-server:
#        jwt:
#          issuer-uri: ${oauth2-client-keycloak}/realms/${client-realm}
#        jwt:
#         keycloak:
#            issuer-uri: ${oauth2-client-keycloak}/realms/${client-realm}
        opaque-token:
          keycloak:
            introspection-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/token/introspect
#              client-id: client
#              client-secret: secret

#  # Doesnt work for java 8 date types
#  jackson:
#    date-format: 'yyyy-MM-ddTHH:mm:ss.sssZ'
#    serialization:
#      write_dates_as_timestamps: false


management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        greeting: true
        http:
          server:
            requests: true


app:
  host-name: --
  api:
    my-user-info: /v1/protected/my/user-info
    my-key-info: /v1/protected/my/key-info
    my-permission-info: /v1/protected/my/permission-info
    my-user-dossier: /v1/protected/my/user-dossier


logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web: TRACE
    com.siukatech.poc.react.backend.module.core: TRACE


